# Generated by Django 4.1.3 on 2022-11-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.CharField(max_length=64)),
                ("date_creation", models.DateField()),
                ("date_update", models.DateField()),
                ("user", models.CharField(max_length=64)),
                ("actives", models.BooleanField()),
            ],
        ),
    ]
